#ifndef COMMANDS_H
#define COMMANDS_H
#include "../term/add.h"
#include "../term/cd.h"
#include "../term/clear.h"
#include "../term/crdir.h"
#include "../term/crfile.h"
#include "../term/del.h"
#include "../term/div.h"
#include "../term/list.h"
#include "../term/mul.h"
#include "../term/pcd.h"
#include "../term/pfc.h"
#include "../term/reboot.h"
#include "../term/rename.h"
#include "../term/sex.h"
#include "../term/sub.h"
#include "../term/ver.h"
#endif
